{{ $values := .Values}}
{{- if .Values.ngcCredentials.password }}
apiVersion: v1
kind: Secret
data:
  {{ .Values.modelRepoGenerator.ngcSecretKey }}: {{ .Values.ngcCredentials.password |  quote }}
metadata:
  creationTimestamp: null
  name: modelpullsecret
  namespace: {{ .Release.Namespace }}
{{- end}}
