apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ngcCredentials.secretName }}
type: Opaque
data:
  password: bmw2cHE4M280cmg1N2Rpc2NucWVudXNwbXM6OGE3MmVmMjAtODNkOS00MDA4LTk5OWMtODJhNmU2MGVhMjE2
