{{ $values := .Values}}
{{- if $values.ngcCredentials.password }}

apiVersion: v1
data:
  .dockerconfigjson: {{ template "ngcPullSecret" . }}
kind: Secret
metadata:
  creationTimestamp: null
  name: imagepullsecret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/dockerconfigjson
{{- end}}
