{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-pods-and-pvcs
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: hub
    namespace: jupyterhub-system
roleRef:
  kind: Role
  name: manage-pods-and-pvcs
  apiGroup: rbac.authorization.k8s.io
{{- end }}
